### ISSUE TITLE
"Injury:injured" and "child" selection in "counterparty in crashes" not working

### ISSUE THREAD

**Issue by OliPi11** [janderk2/roaddanger.org#5]
When pushing the "injury" or "child" buttons in the [counterpary in crashes](https://www.roaddanger.org/statistics/counterparty?period=all&country=UN) section, nothing happens. It is also not possible to deselect "Injury:dead".

**Comment by janderk2** [comment]
Dead were always selected and showing an indication that it was look like a smart ID to me.  Agree that it is not intuitive. I will change it so one can switch it off.

Since a few days you have to hit the Filter button to activate the filter settings. Mainly because there is a text search and searching the database for every character that was typed did not seem like a good idea. But I may just add a delay of a few seconds to the text search field to fix this.

**Comment by janderk2** [comment]
Agree, I'll try something like that.

**Comment by janderk2** [comment]
Fixed in latest version
